name: C/C++ CI

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    -name: test1
      run: cd tests
      run: cd ch_test
      run: ./setup.sh
      run: make run
