name: C/C++ CI

on:
  push:
    branches: [ "origin" ]
  pull_request:
    branches: [ "origin" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./test/ch_test
        
    steps:
    - uses: actions/checkout@v4
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1 # Use the setup action
    - name: setup
      run: ./setup.sh
    - name: run
      run: make run
